---
title: 'Workshop 2: Data visualisation using R'
author: "Fursham Hamid"
output: html_document
---

> ### Overview
><br />
> **Duration**: 2 hours
><br />
><br />
>
> **Objectives**
>
> 1) Format data-frames for visualisation purposes
> 2) State the various available R packages for plotting
> 3) Use ggplot2 to generate publication quality graphics
> 4) Apply geometry, aesthetic, and statistics layers to a ggplot plot
> 5) Manipulate the aesthetics of a plot using different colors, shapes, and lines
> 6) Improve data visualization through transforming scales and paneling by group
> 7) Save a plot created with ggplot to disk
><br />

## Before starting the lesson
Please ensure that you have the latest version of R and RStudio installed on 
your computer. You may refer to this [link](https://datacarpentry.org/R-ecology-lesson/#preparations) 
for step-by-step instructions on downloading these software.  

We will be using two R packages for our tutorial: ggplot2 and ggpubr. 
Please install these packages by typing the following command in RStudio console
```{r eval=FALSE}
install.packages("ggplot2", "ggpubr")
```

<br/ >

## Lesson schedule
||||
|:---|:------------|:------------|
|10:00|[Introduction and overview](https://fursham-h.github.io/R-datascience/articles/2_Data_visualisation_using_R/Lesson_intro.html)| Why visualize data using programming language? |
|10:10|[1. Data structure for plotting ](https://fursham-h.github.io/R-datascience/articles/2_Data_visualisation_using_R/Lesson_intro.html#datastruct) | How should I format my data to facilitate visualisation in R? <br> How do I reshape my data? |
|10:20|2. [R packages for data visualisation](https://fursham-h.github.io/R-datascience/articles/2_Data_visualisation_using_R/Lesson_intro.html#rpackages) | What packages can I use to plot data? |
|10:40|**Break and prepare for hands-on session**||
|11:00|3. [Creating Publication-Quality Graphics with ggplot2](http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/index.html)|  How can I create publication-quality graphics in R?  |
|12:00|Finish| |










